-- Drop existing tables to ensure schema is updated
DROP TABLE IF EXISTS "instructor_qualifications" CASCADE;
DROP TABLE IF EXISTS "instructors" CASCADE;

-- Create instructors table
CREATE TABLE "instructors" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "full_name" text NOT NULL,
    "title" text,
    "workplace" text,
    "experience_years" integer NOT NULL DEFAULT 0,
    "image_url" text,
    "is_verified" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_instructors" PRIMARY KEY ("id"),
    CONSTRAINT "FK_instructors_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- Create instructor_qualifications table
CREATE TABLE IF NOT EXISTS "instructor_qualifications" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "instructor_id" integer NOT NULL,
    "qualification_name" varchar(200) NOT NULL,
    CONSTRAINT "PK_instructor_qualifications" PRIMARY KEY ("id"),
    CONSTRAINT "FK_instructor_qualifications_instructors_instructor_id" FOREIGN KEY ("instructor_id") REFERENCES "instructors" ("id") ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "IX_instructors_user_id" ON "instructors" ("user_id");
CREATE INDEX IF NOT EXISTS "IX_instructor_qualifications_instructor_id" ON "instructor_qualifications" ("instructor_id");
