CREATE TABLE IF NOT EXISTS "medical_records" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer NOT NULL,
    "condition_name" text NOT NULL,
    "description" text,
    "year_diagnosed" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_medical_records" PRIMARY KEY ("id"),
    CONSTRAINT "FK_medical_records_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX "IX_medical_records_user_id" ON "medical_records" ("user_id");
